version: '3.9'
services:
  fpm:
    build: ./
    container_name: swapi_fpm
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
  web:
    image: nginx:latest
    container_name: swapi_web
    environment:
      - FASTCGI_PASS_HOST=fpm
    ports:
      - '${APP_PORT}:8901'
    volumes:
      - ./:/app:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
      - ./docker/nginx/log:/var/log/nginx:delegated
    links:
      - fpm
    depends_on:
      - fpm
